# Generated by Django 5.0.3 on 2024-05-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreanime')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genrefilm')),
                ('serie_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreserietv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreanime')),
                ('genre_film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genrefilm')),
                ('genre_serie_tv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreserietv')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
