# Generated by Django 5.0.3 on 2024-08-16 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('age_limit', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled'), ('Released', 'Released')], default='Ongoing', max_length=20)),
                ('media_type', models.CharField(choices=[('tv_show', 'TV Show'), ('movie', 'Movie'), ('anime', 'Anime')], max_length=10)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateField()),
                ('progression', models.DecimalField(decimal_places=2, max_digits=5)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
