# Generated by Django 5.0.3 on 2024-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie_tv',
            name='serie_id',
        ),
        migrations.AddField(
            model_name='serie_tv',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
