# Generated by Django 5.0.3 on 2024-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='first_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
