# Generated by Django 5.0.3 on 2024-08-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_remove_serie_tv_serie_id_serie_tv_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie_tv',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
    ]
