# Generated by Django 5.0.3 on 2024-08-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_serie_tv_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie_tv',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
