# Generated by Django 5.0.3 on 2024-08-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_alter_serie_tv_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie_tv',
            name='age_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie_tv',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
