# Generated by Django 5.0.3 on 2024-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_alter_serie_tv_age_limit_alter_serie_tv_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie_tv',
            name='number_of_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
