# Generated by Django 5.0.3 on 2024-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_alter_serie_tv_number_of_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='genreserietv',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
