# Generated by Django 5.0.3 on 2024-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_genreserietv_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
