# Generated by Django 5.0.3 on 2024-08-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_alter_anime_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='serie_tv',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
