# Generated by Django 5.0.3 on 2024-05-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenreFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenreSerieTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('age_limit', models.IntegerField()),
                ('release_date', models.DateField()),
                ('number_of_episodes', models.IntegerField()),
                ('image', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=20)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreanime')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('age_limit', models.IntegerField()),
                ('release_date', models.DateField()),
                ('image', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Upcoming', 'Upcoming')], default='Released', max_length=20)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genrefilm')),
            ],
        ),
        migrations.CreateModel(
            name='Serie_TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('age_limit', models.IntegerField()),
                ('release_date', models.DateField()),
                ('number_of_episodes', models.IntegerField()),
                ('image', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=20)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreserietv')),
            ],
        ),
        migrations.CreateModel(
            name='User_content_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.IntegerField()),
                ('date_followed', models.DateField()),
                ('progression', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
