# Generated by Django 5.0.3 on 2024-08-16 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
        ('user_preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoritecontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userfavoritecontent',
            name='media_type',
            field=models.CharField(blank=True, choices=[('anime', 'Anime'), ('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritecontent',
            unique_together={('user', 'media', 'media_type')},
        ),
    ]
