# Generated by Django 5.0.3 on 2024-08-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_genreserietv_tmdb_id'),
        ('user_preferences', '0002_userfavoritecontent_genre_serie_tv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritecontent',
            name='genre_serie_tv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.genreserietv'),
        ),
    ]
