# Generated by Django 5.0.3 on 2024-09-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_alter_userfavoritecontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritecontent',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
