# Generated by Django 5.0.3 on 2024-08-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_alter_film_title_alter_serie_tv_title'),
        ('user_preferences', '0003_alter_userfavoritecontent_genre_serie_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritecontent',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.genreanime'),
        ),
        migrations.AlterField(
            model_name='userfavoritecontent',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.genrefilm'),
        ),
        migrations.AlterField(
            model_name='userfavoritecontent',
            name='genre_serie_tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.genreserietv'),
        ),
        migrations.AlterField(
            model_name='userfavoritecontent',
            name='serie_tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.serie_tv'),
        ),
    ]
